name: build node

on:
  schedule:
    - cron: "0 0 1,15 * *"
  
  push:
    branches:
      - main
    paths:
      - node/**

  workflow_dispatch:

jobs:
  push:
    name: "node_${{ matrix.node }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '16'
          - '16-alpine'
          - '18'
          - '18-alpine'
          - '20'
          - '20-alpine'
          - '22'
          - '22-alpine'

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ghostdevv
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./node
          file: ./node/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/ghostdevv/node:${{ matrix.node }}
